# Generated by Django 4.2.10 on 2024-02-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_messages_room_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
